<?php require_once('header.phtml'); ?>

<div class="container">

	<div>
		<h1>Add New Account</h1>
		<?php echo validation_errors(); ?>
		<form action="<?=base_url('/admin/account/new') ?>" method="post" class="form-horizontal" role="form">
			<div class="form-group">
				<label class="col-sm-2 control-label">UserName</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" placeholder="UserName" name="username" value="<?php echo set_value('username'); ?>" autofocus="autofocus" required="required" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Email address</label>
				<div class="col-sm-10">
					<input type="email" class="form-control"placeholder="Enter email" name="email" value="<?php echo set_value('email'); ?>" required="required" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control" placeholder="Password" name="password" required="required" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Confirm Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password" required="required" />
				</div>
			</div>

			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
		</form>

	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>