<?php require_once('header.phtml'); ?>

<div class="container">

	<div>
		<h1>Edit Account</h1>
		<form method="post" class="form-horizontal" role="form">
			<input type="hidden" name="account_id" value="<?=set_value('account_id', $account_id); ?>" />
			<div class="form-group">
				<label class="col-sm-2 control-label">UserName</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" placeholder="UserName" name="username" value="<?=set_value('username', $username); ?>" autofocus="autofocus" required="required" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Email address</label>
				<div class="col-sm-10">
					<input type="email" class="form-control"placeholder="Enter email" name="email" value="<?=set_value('email', $email); ?>" required="required" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control" placeholder="Password" name="password" />
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">Confirm Password</label>
				<div class="col-sm-10">
					<input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password" />
				</div>
			</div>

			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
		</form>

	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>