<?php require_once('header.phtml'); ?>

<div class="container">

	<div class="text-center">
		<h1>Admin Dashboard</h1>
		<a href="<?=base_url('/admin/user/new') ?>" class="btn btn-primary btn-lg">Add New User</a>
		<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>