<?php require_once('header.phtml'); ?>

<div class="container">

	<div class="text-center">
		<h1>Login</h1>
		<?php echo validation_errors(); ?>
		<form action="<?=base_url('/admin/login') ?>" method="post" role="form" style="max-width: 400px; margin: 0px auto;">
			<div class="form-group">
				<input type="text" class="form-control" placeholder="UserName" name="username" value="<?php echo set_value('username'); ?>" required="required" autofocus="autofocus" />
			</div>
			<div class="form-group">
				<input type="password" class="form-control" placeholder="Password" name="password" value="<?php echo set_value('password'); ?>" required="required" />
			</div>
			<button type="submit" class="btn btn-lg btn-primary btn-block">Submit</button>
		</form>

	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>