<?php require_once('header.phtml'); ?>
<script type="text/javascript" src="<?=base_url('/assets/common/tinymce/tinymce.min.js')?>"></script>
<div class="container">

	<div>
		<h1><?php if(empty($post_id)){?>New Post<?php }else{ ?>Edit Post<?php }?></h1>
		<?php
		//lets have the flashdata overright "$message" if it exists
		if($this->session->flashdata('message'))
		{
			$message = $this->session->flashdata('message');
		}

		if($this->session->flashdata('error'))
		{
			$error  = $this->session->flashdata('error');
		}

		if(function_exists('validation_errors') && validation_errors() != '')
		{
			$error  = validation_errors();
		}
		?>
		</div>

		<?php if (!empty($message)): ?>
			<div class="alert alert-success">
				<a class="close" data-dismiss="alert">×</a>
				<?php echo $message; ?>
			</div>
		<?php endif; ?>

		<?php if (!empty($error)): ?>
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert">×</a>
				<?php echo $error; ?>
			</div>
		<?php endif; ?>
		<form method="post" role="form">
			<input type="hidden" name="post_id" value="<?php echo set_value('post_id', $post_id); ?>" />
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Title" name="title" value="<?php echo set_value('title', $title); ?>" />
			</div>
			<div class="form-group">
				<textarea id="text_content" name="text_content" class="hidden"></textarea>
				<textarea class="form-control" id="content" name="content"><?php echo set_value('content', $content); ?></textarea>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-default" onclick="return beforeSubmit();">Submit</button>
			</div>
		</form>

	</div>

</div><!-- /.container -->

<script type="text/javascript">
	tinymce.init({
		selector: "textarea#content"
	});

	function beforeSubmit(){
		tinymce.triggerSave();
		$('#text_content').val(tinymce.get('content').getContent({format: 'text'}));
	}
</script>
<?php require_once('footer.phtml'); ?>