<?php require_once('header.phtml'); ?>
<script type="text/javascript" src="<?=base_url('/assets/common/tinymce/tinymce.min.js')?>"></script>
<div class="container">

	<div>
		<h1><?php if(empty($post_id)){?>New Post<?php }else{ ?>Edit Post<?php }?></h1>
		<form method="post" role="form">
			<input type="hidden" name="post_id" value="<?php echo set_value('post_id', $post_id); ?>" />
			<div class="form-group">
				<input type="text" class="form-control" placeholder="Title" name="title" value="<?php echo set_value('title', $title); ?>" />
			</div>
			<div class="form-group">
				<textarea id="text_content" name="text_content" class="hidden"></textarea>
				<textarea class="form-control" id="content" name="content"><?php echo set_value('content', $content); ?></textarea>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-default" onclick="return beforeSubmit();">Submit</button>
			</div>
		</form>

	</div>

</div><!-- /.container -->

<script type="text/javascript">
	tinymce.init({
		selector: "textarea#content"
	});

	function beforeSubmit(){
		tinymce.triggerSave();
		$('#text_content').val(tinymce.get('content').getContent({format: 'text'}));
	}
</script>
<?php require_once('footer.phtml'); ?>