<?php require_once('header.phtml'); ?>
<div class="container">

	<div>
		<h1><?php if(!isset($web_app_id)){?>New WebApp<?php }else{ ?>Edit WebApp<?php }?></h1>
		<?php
		//lets have the flashdata overright "$message" if it exists
		if($this->session->flashdata('message'))
		{
			$message = $this->session->flashdata('message');
		}

		if($this->session->flashdata('error'))
		{
			$error  = $this->session->flashdata('error');
		}

		if(function_exists('validation_errors') && validation_errors() != '')
		{
			$error  = validation_errors();
		}
		?>
		</div>

		<?php if (!empty($message)): ?>
			<div class="alert alert-success">
				<a class="close" data-dismiss="alert">×</a>
				<?php echo $message; ?>
			</div>
		<?php endif; ?>

		<?php if (!empty($error)): ?>
			<div class="alert alert-danger">
				<a class="close" data-dismiss="alert">×</a>
				<?php echo $error; ?>
			</div>
		<?php endif; ?>
		<form method="post" role="form">
			<input type="hidden" name="web_app_id" value="<?php echo set_value('web_app_id', $web_app_id); ?>" />
			<div class="form-group">
				<input type="text" class="form-control" name="title" placeholder="Title" value="<?php echo set_value('title', $title); ?>" />
			</div>
			<div class="form-group">
				<input type="text" class="form-control" name="url" placeholder="URL" value="<?php echo set_value('url', $url); ?>" />
			</div>
			<div class="form-group">
				<input type="text" class="form-control" name="appname" placeholder="AppName" value="<?php echo set_value('appname', $appname); ?>" />
			</div>
			<div class="form-group">
				<input type="text" class="form-control" name="remarks" placeholder="Remarks" value="<?php echo set_value('remarks', $remarks); ?>" />
			</div>
			<div class="form-group">
				<textarea name="description" class="form-control" placeholder="Description" value="<?php echo set_value('description', $description); ?>"></textarea>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
		</form>

	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>