<?php require_once('/../header.phtml'); ?>

<link href='<?= base_url("assets")?>/themes/front/base/webapp.css' rel="stylesheet" />

<script>
	$(function() {
		$('.card .add-btn').click(function(){
            $("#add_app_modal .modal-body").html('...');
            $("#add_app_modal").modal('show');
            $("#add_app_modal .modal-body").load("/board/contextList/" + $(this).attr('data-app-id'));
		});
	});

    function add_app_to_board(web_app_id,board_id) {
        $.post("<?= base_url("webapp/addToAccount")?>", {web_app_id: web_app_id, board_id: board_id}, function(data){
            $("#add_app_modal").modal('toggle')
            obj = eval("(" + data + ")");
            alert(obj.message);
        });
    }
</script>
<div class="container">

	<div>
		<ul class="list-inline clearfix">
			<?php foreach($webApps as $webApp){ ?>
			<li class="card">
				<div class="app-logo">
					<a href="<?=base_url('/webapp/'.($webApp->appname ? $webApp->appname : $webApp->web_app_id)) ?>">
						<img src="<?=$webApp->icon_uri ?>" height="32" width="32"/>
					</a>
				</div>
				<div class="app-desc">
					<a class="app-name" href="<?=base_url('/webapp/'.($webApp->appname ? $webApp->appname : $webApp->web_app_id)) ?>"><?=$webApp->title ?></a>
					
					<a class="add-btn" data-app-id="<?=$webApp->web_app_id ?>" href="javascript:void(0);"><b>+</b> Add</a>
					
					<div class="app-meta"><?=$webApp->remarks ?></div>
				</div>
			</li>
			<?php } ?>
		</ul>
	</div>

</div><!-- /.container -->

<!-- modal -->
<div id="add_app_modal" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Pick a board</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
        </div>
    </div>
</div>

<?php require_once('/../footer.phtml'); ?>