<?php require_once('/../header.phtml'); ?>

<link href='<?= base_url("assets")?>/themes/front/base/webapp.css' rel="stylesheet" />
<div class="container">

	<div>
		<div>
			<img src="<?=$webApp->icon_uri ?>" height="32" width="32"/>
		</div>
		<div>
			<a><?=$webApp->title ?></a>
			<div class="app-meta"><?=$webApp->remarks ?></div>
		</div>
	</div>

</div><!-- /.container -->

<?php require_once('/../footer.phtml'); ?>