<?php require_once('header.phtml'); ?>

<div class="container">

	<div class="starter-template">
		<h1>Login</h1>
		<?php echo validation_errors(); ?>
		<form action="<?=base_url('/admin/login') ?>" method="post" class="form-inline" role="form">
			<div class="form-group">
				<label>UserName</label>
				<input type="text" class="form-control" placeholder="UserName" name="username" value="<?php echo set_value('username'); ?>" autofocus="autofocus" />
			</div>
			<div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" class="form-control" placeholder="Password" name="password" value="<?php echo set_value('password'); ?>" />
			</div>
			<button type="submit" class="btn btn-default">Submit</button>
		</form>

	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>