<div class="list-group">
    <?php foreach($boards as $board): ?>
	<?php if(in_array($board->board_id, $board_ids)) { ?>
    <a href="javascript:void(0);" onclick="javascript:$('#add_app_modal').modal('hide');"
	   class="list-group-item list-group-item-warning">
        <?=$board->title ?>
    </a>
	<?php }else{ ?>
	<a href="javascript:void(0);" onclick="add_app_to_board(<?=$web_app_id ?>, <?=$board->board_id ?>)"
	   class="list-group-item">
		<?=$board->title ?>
	</a>
	<?php } ?>
    <?php endforeach; ?>
</div>