<?php require_once('/../header.phtml'); ?>
<div class="container">

	<div>
		<h1><?php if(empty($board_id)){?>New Board<?php }else{ ?>Edit Board<?php }?></h1>
		<form method="post" role="form">
			<input type="hidden" name="board_id" value="<?php echo set_value('board_id', $board_id); ?>" />
			<div class="form-group">
				<input type="text" class="form-control" name="title" placeholder="Title" value="<?php echo set_value('title', $title); ?>" />
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
		</form>

	</div>

</div><!-- /.container -->

<?php require_once('/../footer.phtml'); ?>