<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="<?= base_url("assets")?>/ico/favicon.ico">

	<title>Dashboard</title>

	<link href='<?= base_url("assets")?>/common/bootstrap/css/bootstrap.css' rel="stylesheet" />
	<link href='<?= base_url("assets")?>/common/bootstrap/css/bootstrap-theme.css' rel="stylesheet" />
	<script src="<?= base_url("assets")?>/common/jquery/jquery-1.11.0.min.js"></script>
	<script src='<?= base_url("assets")?>/common/bootstrap/js/bootstrap.js'></script>
</head>
<body>

<div class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">Project name</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="/home">Home</a></li>
				<li><a href="/InfoCenter">InfoCenter</a></li>
				<li><a href="/webapp">WebApp</a></li>
				<li><a href="/account/signup">Join</a></li>
			</ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/board/new">Create Board</a></li>
                        <li><a href="/webapp">Add Link</a></li>
                    </ul>
                </li>
            </ul>
		</div><!--/.nav-collapse -->
	</div>
</div>
<script>
	$('.navbar a[href="/<?=$this->uri->uri_string()?>"]').parent().addClass('active');
</script>

<?php
//lets have the flashdata overright "$message" if it exists
if($this->session->flashdata('message'))
{
	$message = $this->session->flashdata('message');
}

if($this->session->flashdata('error'))
{
	$error  = $this->session->flashdata('error');
}

if(function_exists('validation_errors') && validation_errors() != '')
{
	$error  = validation_errors();
}
?>
</div>

<?php if (!empty($message)): ?>
	<div class="alert alert-success">
		<a class="close" data-dismiss="alert">×</a>
		<?php echo $message; ?>
	</div>
<?php endif; ?>

<?php if (!empty($error)): ?>
<div class="alert alert-danger">
	<a class="close" data-dismiss="alert">×</a>
	<?php echo $error; ?>
</div>
<?php endif; ?>