<?php require_once('header.phtml'); ?>
	<script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script>
<div class="container">

	<div class="text-center">
		<h1>Bootstrap starter template</h1>
		<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
	</div>

</div><!-- /.container -->

<?php require_once('footer.phtml'); ?>