<?php require_once('header.phtml'); ?>

<link href='<?= base_url("assets") ?>/themes/front/base/webapp.css' rel="stylesheet"/>
<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<div class="container">

	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
		<?php foreach ($boards as $board) { ?>
			<div class="panel panel-default">
				<div class="panel-heading" role="tab" id="board-heading-<?= $board->board_id ?>">

					<h4 class="panel-title" data-toggle="collapse" data-target="#board-collapse-<?= $board->board_id ?>"
						aria-expanded="true" aria-controls="board-collapse-<?= $board->board_id ?>">
						<a href="/board/<?=$board->board_id ?>" style="display: inline;"><?= $board->title ?></a>
					</h4>
				</div>
				<div id="board-collapse-<?= $board->board_id ?>" class="panel-collapse collapse in" role="tabpanel"
					 aria-labelledby="board-heading-<?= $board->board_id ?>">
					<div class="panel-body">
						<ul class="list-inline clearfix board">
							<?php foreach ($board->apps as $app) { ?>
								<li class="card">
									<div class="app-logo">
										<a href="<?= $app->url ?>" target="_blank">
											<img src="<?= $app->icon_uri ?>" height="32" width="32"/>
										</a>
									</div>
									<div class="app-desc">
										<a class="app-name" href="<?= $app->url ?>"
										   target="_blank"><?= $app->title ?></a>

										<div class="app-meta"><?= $app->remarks ?></div>
									</div>
								</li>
							<?php } ?>
						</ul>
					</div>
				</div>
			</div>
		<?php } ?>
	</div>
</div><!-- /.container -->

<script>
	$(function() {
		$( ".board" ).sortable();
		//$( "#sortable" ).disableSelection();
	});
</script>
<?php require_once('footer.phtml'); ?>
